const content = [
    {   
        Id : "1",
        type : "tvseries",
        title: "Peaky Blinders" ,
        image: "https://www.hallofseries.com/wp-content/uploads/2022/02/Peaky-Blinders-6-1-930x620.jpg" ,
        description: "Nel 1919, in seguito alla Grande Guerra, i Peaky Blinders, guidati da Thomas (Tommy Shelby), un ex sergente maggiore decorato, si appropriarono di un accumulo di armi dalla fabbrica locale. Winston Churchill, Ministro delle Munizioni, decide di mandare l'ispettore Campbell a Birmingham per recuperarle." ,
        rating: "5" ,
    },
    {   
        Id : "2",
        type : "tvseries",
        title: "Stranger-Things" ,
        image: "https://upload.wikimedia.org/wikipedia/commons/3/38/Stranger_Things_logo.png" ,
        description: "La sera del 6 novembre 1983, in un laboratorio segreto, uno scienziato cerca di fuggire da una misteriosa creatura, Nella vicina città di Hawkins, quattro ragazzini di nome Mike, Will, Lucas e Dustin stanno finendo di giocare a Dungeons & Dragons a casa di Mike. Finito di giocare, Will, Lucas e Dustin tornano a casa loro in bicicletta. Lungo la strada, Will vede uno strano essere che inizia ad inseguirlo, quindi scappa attraverso il bosco fino a casa sua; dopo aver cercato di chiamare qualcuno, viene raggiunto dalla creatura che lo fa scomparire improvvisamente nel nulla", 
        rating: "4" ,
    },
    {   
        Id : "3",
        type : "tvseries",
        title: "how i met your mother" ,
        image: "https://prod-ripcut-delivery.disney-plus.net/v1/variant/disney/BEA544D7476F6C33E23CB73494F462BAF5F9A247B41B335F74094773F4112C03/scale?width=1200&aspectRatio=1.78&format=jpeg" ,
        description: "Una lunga storia. Nel 2030 Ted Mosby inizia a raccontare ai suoi due figli come ha conosciuto la loro madre. La storia risale al 2005 quando Marshall, migliore amico di Ted, gli rivela di aver deciso di chiedere a Lily, la sua fidanzata, di sposarlo." ,
        rating: "5" ,
    },
    {    
        Id : "4",
        type : "tvseries",
        title: "Elitè" ,
        image: "https://www.ilnotiziario.net/wp/wp-content/uploads/2020/03/43694609_2214324695501986_4779073710134919168_o.jpg" ,
        description: "A causa di un terremoto, la loro scuola viene distrutta e gli studenti vengono smistati in altri istituti. Tre di loro vanno a finire nella scuola migliore e più esclusiva della Spagna. I tre, arrivati nell'istituto dovranno scontrarsi con dei ragazzi ricchi e viziati, a cui non manca mai nulla." ,
        rating: "2.5" ,
    },
    {
        Id : "5",
        type : "tvseries",
        title: "Breacking-bad" ,
        image: "https://www.viverediscrittura.it/VDS/wp-content/uploads/2018/04/Scrivere-come-i-grandi-lezioni-da-Breaking-Bad.jpg" ,
        description: "Walter White è un insegnante di chimica con una famiglia, una vita normale, che improvvisamente viene sconvolta da una diagnosi di cancro. Disperato all'idea di lasciare la sua famiglia senza mezzi di sostentamento e grazie a un incontro con un suo ex studente che ha preso una cattiva strada, Jesse Pinkman, Walter decide di sfruttare le sue doti di chimico e darsi all'illegalità, creando e distribuendo un tipo di meta-anfetamina purissima che gli da' la possibilità di accumulare grosse quantità di danaro... ma frequentare un ambiente criminale, cambia inevitabilmente e inesorabilmente l'atteggiamento di Walter, rendendolo un uomo molto pericoloso che è meglio non avere come nemico..." ,
        rating: "5" ,
    },
    {
        Id : "6",
        type : "film",
        title: "The Amazing Spider-man" ,
        image: "https://m.media-amazon.com/images/I/91cAWkfjPEL._SL1500_.jpg" ,
        description: "Quando il giovane scolaretto adolescente Peter Parker indaga sul mistero della morte dei suoi genitori e sulla ricerca di suo padre, si ritrova morso da un ragno radioattivo che aumenta i suoi sensi, rafforza i suoi muscoli e gli consente di arrampicarsi sui muri." ,
        rating: "3.5" ,
    },
    {
        Id : "7",
        type : "film",
        title: "Django" ,
        image: "https://www.rai.it/dl/img/2021/03/02/1600x900_1614673938910_2021.03.02%20-%20Django%20Unchained.jpg" ,
        description: "Il cacciatore di taglie di origine tedesca dottor King Schultz, su un carretto da dentista, è alla ricerca dei fratelli Brittle, per consegnarli alle autorità preferibilmente morti e incassare così la ricompensa. Per scovarli, libera dalle catene lo schiavo Django, promettendogli la libertà a missione completata." ,
        rating: "4" ,
    },
    {
        Id : "8",
        type : "film",
        title: "Suicide Squad" ,
        image: "https://pad.mymovies.it/filmclub/2015/05/010/locandina.jpg" ,
        description: "Quando il mondo è sconvolto dalla morte di Superman, il governo deve correre ai ripari. L'agente Amanda Waller (Viola Davis) affida al colonello Rick Flag (Joel Kinnaman) il compito di liberare e addestrare una squadra di super cattivi, rinchiusi in isolamento nel carcere Belle Reve." ,
        rating: "2" ,
    },
    {
        Id : "9",
        type : "film",
        title: "Venom" ,
        image: "https://darumaview.it/wp-content/uploads/2018/10/venom-recensione-film-copertina-.jpg" ,
        description: "Il simbionte di Brock è l'unico dei quattro esemplari sopravvissuto, ed Eddie viene attaccato dai mercenari impiegati da Drake per recuperarlo, ma esso si impossessa del corpo di Eddie, trasformandolo in una creatura mostruosa e altamente letale nel respingere e neutralizzare gli attacchi dei nemici." ,
        rating: "2.5" ,
    },
    {
        Id : "10",
        type : "film",
        title: "Bastardi Senza Gloria" ,
        image: "https://m.media-amazon.com/images/I/71t14nj8cKL._SL1500_.jpg" ,
        description: "Nella Francia occupata dai nazisti, la giovane ebrea Shosanna Dreyfus assiste al massacro di tutta la propria famiglia per mano del colonnello tedesco Hans Landa, soprannominato cacciatore di ebrei, per la sua abilità nel fiutare i loro nascondigli." ,
        rating: "4.5" ,
    },

];

export default content;